version: "3.7"

services:
  postgres:
    container_name: freelancer-flow-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - freelancer-flow-network
    restart: unless-stopped

  keycloak:
    container_name: freelancer-keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev --verbose
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://freelancer-flow-db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    restart: always
    networks:
      - freelancer-flow-network


networks:
  freelancer-flow-network:
    driver: bridge

volumes:
  postgres:
    driver: local
